#include <iostream> // Required for input (cin) and output (cout)
#include <cstdlib>  // Required for random number generation functions (rand, srand)
#include <ctime>    // Required for time() function, used to seed the random number generator

using namespace std;

// Main function where the program execution begins
int main() {
    // 1. Setup the Random Number Generator (RNG)
    // The time(0) function returns the current time, which is different every second.
    // Using it to seed the RNG ensures the number generated by rand() is different each time the program runs.
    srand(time(0));

    // 2. Generate the Secret Number
    // rand() % 100 generates a number between 0 and 99.
    // Adding 1 shifts the range to be between 1 and 100 (inclusive).
    int secretNumber = (rand() % 100) + 1;
    int guess = 0;
    int attempts = 0;

    cout << "=======================================" << endl;
    cout << "  Welcome to the Guess the Number Game " << endl;
    cout << "=======================================" << endl;
    cout << "I have picked a secret number between 1 and 100." << endl;
    cout << "Can you guess it?" << endl;

    // 3. Start the Game Loop
    // The loop continues indefinitely until the user guesses correctly (using 'break')
    while (true) {
        cout << "\nEnter your guess: ";

        // Basic input validation to handle non-numeric input
        if (!(cin >> guess)) {
            cout << "Invalid input! Please enter a number." << endl;
            // Clear the error flags on cin
            cin.clear();
            // Discard the invalid input from the buffer
            cin.ignore(10000, '\n');
            continue; // Skip the rest of the loop and ask for input again
        }

        // Check if the guess is within the desired range (optional, but good practice)
        if (guess < 1 || guess > 100) {
            cout << "That number is outside the 1-100 range. Try again." << endl;
            continue;
        }

        // Increment the number of attempts
        attempts++;

        // 4. Provide Feedback
        if (guess < secretNumber) {
            cout << "Too low! Try a higher number." << endl;
        } else if (guess > secretNumber) {
            cout << "Too high! Try a lower number." << endl;
        } else {
            // 5. Success Condition
            cout << "\n***************************************" << endl;
            cout << "*** CONGRATULATIONS! You got it! ***" << endl;
            cout << "The secret number was: " << secretNumber << endl;
            cout << "You guessed it in " << attempts << " attempts." << endl;
            cout << "***************************************" << endl;
            break; // Exit the loop and end the game
        }
    }

    return 0; // Indicate successful program execution
}